language: node_js
node_js:
  - "node"
script: 
- jshint ES6/myScript.js ES6/dataStorage.js
- npm run build
branches:
only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 
